version: '2'
services:
  db:
    image: postgres
    container_name: happyfeed_db
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  web:
    env_file: .env.production
    container_name: happyfeed_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/happyfeed
    links:
      - db
    depends_on:
      - db
