version: '2'
services:
  db:
    env_file: .env
    image: mysql
    container_name: happyfeed_mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  web:
    env_file: .env
    container_name: happyfeed_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/happyfeed
    links:
      - db
    depends_on:
      - db
