version: '2'
services:
  db:
    env_file: .env
    image: mysql
    container_name: happyfeed_mysql
    ports:
      - "3306:3306"
  web:
    env_file: .env
    container_name: happyfeed_web
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/happyfeed
    links:
      - db
    depends_on:
      - db
